#!/bin/bash

export PGPASSWORD="nocodbpassword"

psql -U nocodb -d realtoken -c "
    DROP TABLE IF EXISTS real_tokens CASCADE;

    CREATE TABLE real_tokens (
        full_name VARCHAR(255),
        short_name VARCHAR(255),
        symbol VARCHAR(255),
        product_type VARCHAR(255),
        token_price DECIMAL(10,2),
        canal VARCHAR(255),
        currency VARCHAR(255),
        total_tokens INT,
        total_tokens_reg_summed INT,
        uuid VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
        ethereum_contract VARCHAR(255),
        x_dai_contract VARCHAR(255),
        gnosis_contract VARCHAR(255),
        goerli_contract VARCHAR(255),
        total_investment DECIMAL(12,2),
        gross_rent_year DECIMAL(12,2),
        gross_rent_month DECIMAL(12,2),
        property_management DECIMAL(10,2),
        property_management_percent DECIMAL(5,2),
        realt_platform DECIMAL(10,2),
        realt_platform_percent DECIMAL(5,2),
        insurance DECIMAL(10,2),
        property_taxes DECIMAL(10,2),
        utilities DECIMAL(10,2),
        initial_maintenance_reserve DECIMAL(10,2),
        net_rent_year DECIMAL(12,2),
        net_rent_month DECIMAL(12,2),
        net_rent_day DECIMAL(12,4),
        net_rent_day_per_token DECIMAL(12,4),
        net_rent_month_per_token DECIMAL(12,4),
        net_rent_year_per_token DECIMAL(12,4),
        annual_percentage_yield DECIMAL(12,4),
        latitude DECIMAL(10,6),
        longitude DECIMAL(10,6),
        marketplace_link VARCHAR(255),
        property_type INT,
        property_type_name VARCHAR(255),
        square_feet INT,
        lot_size INT,
        bedroom_bath VARCHAR(255),
        has_tenants BOOLEAN,
        rented_units INT,
        total_units INT,
        term_of_lease VARCHAR(255),
        renewal_date VARCHAR(255),
        section_8_paid DECIMAL(10,2),
        subsidy_status VARCHAR(255),
        subsidy_status_value VARCHAR(255),
        subsidy_by VARCHAR(255),
        sell_property_to VARCHAR(255),
        secondary_marketplace TEXT,
        secondary_marketplaces TEXT,
        blockchain_addresses TEXT,
        underlying_asset_price DECIMAL(12,2),
        renovation_reserve DECIMAL(10,2),
        property_maintenance_monthly DECIMAL(10,2),
        series_number INT,
        construction_year INT,
        construction_type VARCHAR(255),
        roof_type VARCHAR(255),
        asset_parking VARCHAR(255),
        foundation VARCHAR(255),
        heating VARCHAR(255),
        cooling VARCHAR(255),
        token_id_rules INT,
        rent_calculation_type VARCHAR(255),
        realt_listing_fee_percent DECIMAL(5,2),
        realt_listing_fee DECIMAL(10,2),
        miscellaneous_costs DECIMAL(10,2),
        property_stories INT,
        rental_type VARCHAR(255),
        neighborhood VARCHAR(255),
        origin_secondary_marketplaces TEXT,
        initial_launch_date TIMESTAMP,
        last_update TIMESTAMP,
        rent_start_date TIMESTAMP,
        image_links TEXT
    );
"